// Playwright Configuration for TechQuest.AI Landing Page
// Location: landing-page/playwright.config.js (same folder as package.json)
// https://playwright.dev/docs/test-configuration

const { defineConfig } = require('@playwright/test');
const fs = require('fs');
const path = require('path');

module.exports = defineConfig({
  testDir: './',
  // Look for tests in same folder as this config
  
  // Run tests in parallel
  fullyParallel: true,
  
  // Fail fast on CI
  forbidOnly: !!process.env.CI,
  
  // Retry flaky tests
  retries: process.env.CI ? 2 : 0,
  
  // Workers: 1 to prevent screenshot collisions when running tests in parallel
  workers: 1,
  
  // Reporter - JSON for automation + line for local
  reporter: [
    ['json', { outputFile: 'test-results/results.json' }],
    ['line'], // Simple output for local
  ],
  
  // Shared settings for all tests
  use: {
    baseURL: 'https://robertc30.github.io/landing-page',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    timeout: 30000,
    actionTimeout: 10000,
  },
  
  // Projects for different browsers/devices
  projects: [
    {
      name: 'desktop',
      use: { 
        viewport: { width: 1280, height: 720 },
      },
    },
    {
      name: 'mobile-chrome',
      use: { 
        viewport: { width: 390, height: 844 }, // iPhone 12
        userAgent: 'Mozilla/5.0 (iPhone 12; CPU OS 14_0 like Mac OS X)',
      },
    },
    {
      name: 'mobile-safari',
      use: { 
        viewport: { width: 390, height: 844 },
        userAgent: 'Mozilla/5.0 (iPhone; CPU OS 14_0 like Mac OS X)',
      },
    },
  ],
  
  // Output directory
  outputDir: 'test-results/',
  
  // Expect assertions
  expect: {
    timeout: 5000,
  },
  
  // Generate QC report after all tests
  // This runs after the test suite completes
  on('done', async (result) => {
    const fs = require('fs');
    const path = require('path');
    
    const date = new Date().toISOString().split('T')[0];
    const qcDir = `../qc/${date}`;
    
    // Ensure directories exist
    fs.mkdirSync(qcDir, { recursive: true });
    fs.mkdirSync(`${qcDir}/screenshots`, { recursive: true });
    fs.mkdirSync(`${qcDir}/traces`, { recursive: true });
    fs.mkdirSync(`${qcDir}/test-results`, { recursive: true });
    
    // Copy test results
    if (fs.existsSync('test-results')) {
      fs.cpSync('test-results', `${qcDir}/test-results`, { recursive: true });
    }
    
    // Copy screenshots
    if (fs.existsSync('screenshots')) {
      fs.cpSync('screenshots', `${qcDir}/screenshots`, { recursive: true });
    }
    
    // Copy traces
    if (fs.existsSync('test-results')) {
      fs.readdirSync('test-results')
        .filter(f => f.endsWith('.zip'))
        .forEach(f => {
          fs.copyFileSync(
            `test-results/${f}`,
            `${qcDir}/traces/${f}`
          );
        });
    }
    
    // Generate summary report
    const summary = {
      timestamp: new Date().toISOString(),
      status: result.status,
      tests: result.tests.length,
      failures: result.failures,
      duration: result.duration,
      artifacts: {
        screenshots: fs.existsSync(`${qcDir}/screenshots`)
          ? fs.readdirSync(`${qcDir}/screenshots`).length
          : 0,
        traces: fs.existsSync(`${qcDir}/traces`)
          ? fs.readdirSync(`${qcDir}/traces`).filter(f => f.endsWith('.zip')).length
          : 0,
      }
    };
    
    fs.writeFileSync(
      `${qcDir}/summary.json`,
      JSON.stringify(summary, null, 2)
    );
    
    // Write markdown summary
    const mdSummary = `# Visual QC Summary - ${date}

**Date:** ${summary.timestamp}
**Status:** ${summary.status}
**Tests:** ${summary.tests}
**Failures:** ${summary.failures}
**Duration:** ${summary.duration}ms

## Artifacts

| Type | Count |
|------|-------|
| Screenshots | ${summary.artifacts.screenshots} |
| Traces | ${summary.artifacts.traces} |
| Test Results | [View](./test-results/) |

## Files

- \`${qcDir}/screenshots/\` - Evidence screenshots
- \`${qcDir}/traces/\` - Replayable traces
- \`${qcDir}/test-results/\` - Full test results

---
Generated by Playwright Visual QC
`;
    
    fs.writeFileSync(`${qcDir}/SUMMARY.md`, mdSummary);
    
    console.log(`\n✓ QC report generated: ${qcDir}/SUMMARY.md`);
    console.log(`  - Screenshots: ${summary.artifacts.screenshots}`);
    console.log(`  - Traces: ${summary.artifacts.traces}`);
  }),
});

// Helper: Generate artifact paths for GitHub Actions
function getArtifactPaths() {
  return [
    'screenshots/',
    'test-results/',
    'test-results/trace.zip',
  ];
}

module.exports.getArtifactPaths = getArtifactPaths;
